### ISSUE TITLE
Operations after = does not work. 

### ISSUE THREAD

**Issue by saki18** [SquaresAndCubes/CSCI497_Calculator#13]
Operations after = does not work. 

**how to reproduce**

1. click on 1+2=
3. at now it should be 3. try adding another 2.

![bug](https://user-images.githubusercontent.com/8292650/62841844-91d1f980-bc7a-11e9-8e30-153b24a4a543.gif)

**expected result:** 
when answer shows three and then adding 2 it should say 5.

**actual result** 
it will display the last number pressed. 

Windows 10, 1809. 
Visual Studio 2019

**Comment by SquaresAndCubes** [comment]
Can now perform operations after equals.

![afterEquals](https://user-images.githubusercontent.com/20231014/62994352-a2b87180-be18-11e9-9fde-1a51acc67dd6.gif)
