### ISSUE TITLE
+/- button not working

### ISSUE THREAD

**Issue by SquaresAndCubes** [SquaresAndCubes/CSCI497_Calculator#6]

**Comment by DBeveridge501** [comment]
Functionality was given to the button's operation code added as follows:
(MainWindow.xml.cs)
 private void BtnPositiveNegative_Click(object sender, RoutedEventArgs e)
        {
            txtAnswers.Text = thisCalculator.PosNag();
        }

(CalculatorClass.cs)

public String PosNag()
        {
            
                if(number2 != "")
                {
                    posNeg = double.Parse(number2) * -1;

                    number2 = Convert.ToString(posNeg);

                    posNeg = 0;

                    return number2.ToString();
                }
                else if(results != 0)
            {
                results = results * -1;

                return results.ToString();
            }
                else
                {
                    posNeg = double.Parse(number1) * -1;

                    number1 = Convert.ToString(posNeg);

                    posNeg = 0;

                    return number1.ToString();
                }
                
           
        }

**Comment by DBeveridge501** [comment]
Functionality was given to the button's operation code added as follows:
(MainWindow.xml.cs)
private void BtnPositiveNegative_Click(object sender, RoutedEventArgs e)
{
txtAnswers.Text = thisCalculator.PosNag();
}

(CalculatorClass.cs)

public String PosNag()
{

            if(number2 != "")
            {
                posNeg = double.Parse(number2) * -1;

                number2 = Convert.ToString(posNeg);

                posNeg = 0;

                return number2.ToString();
            }
            else if(results != 0)
        {
            results = results * -1;

            return results.ToString();
        }
            else
            {
                posNeg = double.Parse(number1) * -1;

                number1 = Convert.ToString(posNeg);

                posNeg = 0;

                return number1.ToString();
            }
            
       
    }
